# docker-compose.yml
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      # persist the results log
      - ./backend/logs:/usr/src/app/logs
      # override the baked-in config folder with your local one
      - ./backend/config:/usr/src/app/config:ro
    environment:
      NODE_ENV: production
